config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :campaigns, only: %i[index show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :votes
  has_many :candidates
  
  validates :name, presence: true, uniqueness: true

  def valid_votes
    votes.joins(:campaign, :candidate)
         .where(validity: "during")
         .where.not(campaigns: { id: nil })
         .where.not(candidates: { id: nil })
         .count
  end
  

  def non_valid_votes
    votes.where(validity: ['pre', 'post']).count
  end

  def count_errors
    votes.where(candidate: [Candidate.where(name: ''), nil]).count
  end

end

app/models/candidate.rb
class Candidate < ApplicationRecord
 belongs_to :campaign
 has_many :votes, foreign_key: :candidate_id

 validates :name, uniqueness: { scope: :campaign_id }

  def score
    votes.where(validity: 'during').count
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :campaign
  belongs_to :candidate, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  
  def index 
    @campaigns = Campaign.joins(:votes).distinct
  end

  def show
    @campaign = Campaign.find(params[:id])
    @candidates = @campaign.candidates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campaigns/index.html.erb
 <div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-6xl font-bold font-mono text-slate-700 sm:text-3xl tracking-wide">Welcome to the TV SMS Voting App</h1>
      <p class="text-md pt-8 leading-7 tracking-wide text-slate-700 sm:text-3xl fonto-mono tracking-light">Select a campaign</p>
    </div>
  </div>

  <div class="flex w-full mt-6">
    <ul role="list" class="divide-y divide-gray-200 overflow-hidden text-center bg-white w-1/2 shadow-lg ring-1 ring-gray-900/5 sm:rounded-xl">
      <% @campaigns.each do |campaign| %>
        <%= link_to campaign_path(campaign), class: "block" do %>
          <li class="relative flex font-mono justify-between tracking-wide gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6">
            <%= campaign.name %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

 

app/views/campaigns/show.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-bold leading-7 text-slate-700 sm:truncate font-mono sm:text-3xl tracking-wide">Metrics Page for campaign:  <%= @campaign.name %></h1>
      <h3 class="mt-2 text-lg font-medium text-blue-900 font-mono">Non-valid votes: <%= @campaign.non_valid_votes %></h3>
      <h3 class="mt-2 text-lg font-medium text-orange-700 font-mono">Errors count: <%= @campaign.count_errors %></h3>
    </div>
  </div>

  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-600">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-center text-md font-semibold text-gray-900 sm:pl-0">
                Name
              </th>
              <th scope="col" class="px-3 py-3.5 text-center text-md font-semibold text-gray-900">
                Score
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <% @campaign.candidates.each do |candidate| %>
              <% unless candidate.name.blank? %>
                <tr>
                  <td class="whitespace-nowrap text-center px-3 py-4 text-md text-gray-500"><%= candidate.name %></td>
                  <td class="whitespace-nowrap text-center px-3 py-4 text-md text-gray-500"><%= candidate.score %></td>
                </tr>
              <% end %> 
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <%= link_to campaigns_path do %>
    <div type="button" class="mt-6 rounded-md bg-indigo-600 px-2 py-6 text-center text-md font-normal font-mono text-white shadow-sm hover:bg-indigo-500">
     Back to campaigns
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvSmsVotingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="mx-auto mt-28 px-5 flex w-1/2">
      <%= yield %>
    </main>
  </body>
</html>